#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" \
    && . "utils"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

create_directories() {

    declare -a DIRECTORIES=(
        "$HOME/git"
        "$HOME/go"
        "$HOME/logs"
        "$HOME/notes"
        "$HOME/private"
        "$HOME/.local"
        "$HOME/.local/bin"
        "$HOME/.local/share"
        "$HOME/.config/alacritty"
        "$HOME/.config/Code\ -\ OSS/User/"
        "$HOME/.config/dunst"
        "$HOME/.config/mpv/scripts"
        "$HOME/.config/mpv/scripts"
        "$HOME/.config/sway"
        "$HOME/pictures/screenshots"
    )

    for i in "${DIRECTORIES[@]}"; do
        mkd "$i"
    done

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

main() {
    print_in_purple "\n • Create directories\n\n"
    create_directories
}

main
