#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" &&
  . "./utils_install" &&
  . "./utils"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

print_in_purple "\n • Installs\n\n"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

install_package_manager

enable_multilib

update

print_in_purple "\n   Browsers\n\n"

install_package "firefox"

print_in_purple "\n   Development\n\n"

install_package "clang"
install_package "code"
install_package "ctags"
install_package "delve"
install_package "docker"
install_package "docker-compose"
install_package "fd"
install_package "flake8"
install_package "fzf"
install_package "git"
install_package "gitg"
install_package "go"
install_package "hugo"
install_package "ipython"
install_package "jdk-openjdk"
install_package "kdiff3"
install_package "kubectl"
install_package "kubectx"
install_package "minikube"
install_package "neovim"
install_package "npm"
install_package "prettier"
install_package "python"
install_package "python-black"
install_package "python-language-server"
install_package "python-pip"
install_package "python-pynvim"
install_package "python-sqlparse"
install_package "python-virtualenv"
install_package "ripgrep"
install_package "rust"
install_package "shellcheck"
install_package "shfmt"
install_package "texlive-science"
install_package "yarn"

print_in_purple "\n   Image Tools\n\n"

install_package "inkscape"
install_package "imagemagick"

print_in_purple "\n   Miscellaneous\n\n"

install_package "acpi"
install_package "aspell-en"
install_package "bat"
install_package "bind-tools"
install_package "bleachbit"
install_package "brotli"
install_package "calibre"
install_package "colordiff"
install_package "diff-so-fancy"
install_package "dust"
install_package "exa"
install_package "imv"
install_package "keepassxc"
install_package "lazygit"
install_package "libqalculate"
install_package "moreutils"
install_package "mpv"
install_package "ncdu"
install_package "nnn"
install_package "tk"
install_package "tlp"
install_package "tokei"
install_package "translate-shell"
install_package "transmission-cli"
install_package "virtualbox"
install_package "wine"
install_package "xclip"
install_package "youtube-dl"
install_package "zathura"
install_package "zathura-pdf-poppler"

install_nnn_plugins

print_in_purple "\n   Fonts\n\n"

install_package "noto-fonts-emoji"
install_package "powerline-fonts"
install_package "ttf-font-awesome"
install_package "ttf-hack"
install_package "ttf-nerd-fonts-symbols"

print_in_purple "\n   Penetration testing\n\n"

install_blackarch_repo
install_package "aircrack-ng"
install_package "bettercap"
install_package "dirb"
install_package "hydra"
install_package "macchanger"
install_package "nmap"
install_package "reaver"
install_package "whatweb"
install_package "wireshark-qt"

print_in_purple "\n   Utilities\n\n"

install_package "alacritty"
install_package "atool"
install_package "cups"
install_package "curl"
install_package "firejail"
install_package "htop"
install_package "httpie"
install_package "jq"
install_package "lsof"
install_package "neofetch"
install_package "net-tools"
install_package "nethogs"
install_package "nm-connection-editor"
install_package "ntfs-3g"
install_package "p7zip"
install_package "rclone"
install_package "rkhunter"
install_package "strace"
install_package "system-config-printer"
install_package "tcpdump"
install_package "tmux"
install_package "unzip"
install_package "vnstat"
install_package "wireguard-dkms"
install_package "wireguard-tools"
install_package "ytop"
install_package "zsh"
install_ohmyzsh

print_in_purple "\n   Sway\n\n"

install_package "alsa-utils"
install_package "bemenu"
install_package "blueman"
install_package "brightnessctl"
install_package "dmenu"
install_package "grim"
install_package "libappindicator-gtk3"
install_package "libnotify"
install_package "libpipewire02"
install_package "mako"
install_package "materia-gtk-theme"
install_package "networkmanager"
install_package "pamixer"
install_package "pavucontrol"
install_package "pipewire"
install_package "pulseaudio-git" # TODO - until pulseaudio 14.0 gets released
#install_package "pulseaudio-alsa"
#install_package "pulseaudio-bluetooth"
install_package "qt5-wayland"
install_package "slurp"
install_package "sof-firmware"
install_package "sway"
install_package "swayidle"
install_package "swaylock"
install_package "waybar"
install_package "wdisplays"
install_package "wl-clipboard"
install_package "xorg-server-xwayland"

print_in_purple "\n   GO packages\n\n"

install_go_package "github.com/odeke-em/drive/cmd/drive" "drive"
install_go_package "github.com/swaggo/swag/cmd/swag" "swag"
install_go_package "golang.org/x/tools/cmd/godoc" "godoc"
install_go_package "golang.org/x/tools/gopls" "gopls"

print_in_purple "\n   JS packages\n\n"

install_npm_package "bash-language-server"
install_npm_package "javascript-typescript-langserver"
install_yarn_package "@mermaid-js/mermaid-cli" "mermaid-cli"

print_in_purple "\n   AUR packages\n\n"

install_package "azure-cli"
install_package "bitwarden-bin"
install_package "bitwarden-cli"
install_package "circleci-cli-bin"
install_package "clipman"
install_package "downgrade"
install_package "exercism-bin"
install_package "github-cli"
install_package "go-swagger"
install_package "golangci-lint"
install_package "google-chrome"
install_package "hfsprogs"
install_package "i3-battery-popup-git"
install_package "joplin"
install_package "kubeval"
install_package "librewolf-bin" # @todo - settings missing
install_package "networkmanager-dmenu-git"
install_package "postman-bin"
install_package "python-grip"
install_package "python-notedown"
install_package "restic-git"
install_package "slack-desktop"
install_package "spotify"
install_package "spotify-tui"  # @todo - manual config with client/secret
install_package "spotifyd-bin" # @todo - config missing, spotifyd.conf, notification.sh, systemd service
install_package "subliminal"
install_package "teamviewer"
install_package "wlr-randr"
install_package "x11docker"
install_package "xdg-desktop-portal-wlr"
install_package "zeal"

./nvim
./code

autoremove
clean_up_cache
