#!/bin/bash


cd "$(dirname "${BASH_SOURCE[0]}")" &&
  . "./utils_install" &&
  . "./utils"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

print_in_purple "\n • Installs\n\n"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

install_package_manager

enable_multilib

update

print_in_purple "\n   Browsers\n\n"

install_package "firefox"

print_in_purple "\n   Development\n\n"

install_package "clang"
install_package "ctags"
install_package "code"
install_package "delve"
install_package "docker"
install_package "fd"
install_package "fzf"
install_package "git"
install_package "go"
install_package "hugo"
install_package "kdiff3"
install_package "neovim"
install_package "jdk-openjdk"
install_package "python"
install_package "python-virtualenv"
install_package "ripgrep"
install_package "rust"
install_package "shellcheck"
install_package "shfmt"
install_package "texlive-science"
install_package "tmux"
install_package "yapf"

print_in_purple "\n   Image Tools\n\n"

install_package "gimp"
install_package "imagemagick"

print_in_purple "\n   Miscellaneous\n\n"

install_package "acpi"
install_package "aspell-en"
install_package "bat"
install_package "bind-tools"
install_package "bleachbit"
install_package "brotli"
install_package "caprine"
install_package "calibre"
install_package "colordiff"
install_package "diff-so-fancy"
install_package "libqalculate"
install_package "keepassxc"
install_package "mpv"
install_package "moreutils"
install_package "ncdu"
install_package "nnn"
install_package "sxiv"
install_package "tlp"
install_package "tk"
install_package "transmission-cli"
install_package "virtualbox" # NOT WORKING
install_package "wine"
install_package "xclip"
install_package "youtube-dl"
install_package "zathura"
install_package "zathura-pdf-poppler"

print_in_purple "\n   Fonts\n\n"

install_package "powerline-fonts"
install_package "ttf-font-awesome"
install_package "ttf-hack"
install_package "ttf-nerd-fonts-symbols"

print_in_purple "\n   Penetration testing\n\n"

install_blackarch_repo
install_package "aircrack-ng"
install_package "bettercap"
install_package "dirb"
install_package "hydra"
install_package "macchanger"
install_package "reaver"
install_package "whatweb"
install_package "nmap" "nmap"
install_package "wireshark-qt"

print_in_purple "\n   Utilities\n\n"

install_package "alacritty"
install_package "atool"
install_package "curl"
install_package "firejail"
install_package "htop"
install_package "neofetch"
install_package "net-tools"
install_package "nethogs"
install_package "rkhunter"
install_package "tcpdump"
install_package "vnstat"
install_package "wireguard-dkms"
install_package "wireguard-tools"
install_package "zsh"

# TODO - oh my zsh

print_in_purple "\n   Sway\n\n"

install_package "blueman"
install_package "dmenu"
install_package "grim"
install_package "libnotify"
install_package "light"
install_package "mako"
install_package "networkmanager"
install_package "pamixer"
install_package "pavucontrol-qt"
install_package "pulseaudio"
install_package "pulseaudio-alsa"
install_package "pulseaudio-bluetooth"
install_package "slurp"
install_package "sway"
install_package "swayidle"
install_package "swaylock"
install_package "qt5-wayland"
install_package "xorg-server-xwayland"
install_package "wl-clipboard"

print_in_purple "\n   AUR packages\n\n"

install_package "clipman"
install_package "downgrade"
install_package "exercism-bin"
install_package "hfsprogs"
install_package "google-chrome"
install_package "i3-battery-popup-git"
install_package "networkmanager-dmenu-git"
install_package "python-grip"
install_package "wlr-randr"
install_package "joplin"
install_package "restic-git"
install_package "spotify"
install_package "teamviewer"

./nvim
./code

autoremove
clean_up_cache
