#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" &&
  . "./utils_install" &&
  . "./utils"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

install_spacevim() {

  declare -r SPACEVIM_DIR="$HOME/.SpaceVim/"
  declare -r SPACEVIM_SCRIPT="https://spacevim.org/install.sh"

  if [ ! -d "$SPACEVIM_DIR" ]; then
    execute "curl -sLf $SPACEVIM_SCRIPT | bash -s -- --install neovim" "Install SpaceVim"
  fi

}

update_plugins() {

  execute \
    "nvim +SPUpdate SpaceVim +sleep 0.1 +qall" \
    "Update SpaceVim"

  execute \
    "nvim +SPUpdate +sleep 0.1 +qall" \
    "Update SpaceVim plugins"
# TODO hellp
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

main() {

  print_in_purple "\n   NeoVim with SpaceVim <3\n\n"

  install_spacevim
  update_plugins

  printf "\n"

}

main
