#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" \
    && . "utils"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

print_in_purple "\n   Development configuration\n\n"

execute "(getent group docker | grep $USER) || sudo usermod -aG docker $USER" \
        "No sudo required for docker users (logout required!)"

execute "getent group pcap || (sudo groupadd pcap && sudo usermod -aG pcap $USER)" \
        "Create pcap group (logout required!)"

execute "sudo chgrp pcap /usr/sbin/tcpdump && sudo chmod 750 /usr/sbin/tcpdump \
         && sudo setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump" \
        "No sudo required for tcpdumping"

execute "(getent group vboxusers | grep $USER) || sudo usermod -aG vboxusers $USER" \
        "User added to vboxusers group (logout required!)"

execute "sudo firecfg" "Firejail auto config" # consider activating firefox-common-addons.inc

execute "sudo timedatectl set-ntp true" "Turn on ntp"

execute "sudo systemctl enable tlp" "Turn on tlp"

execute "sudo systemctl enable NetworkManager.service" "Turn on networkmanager"

execute "systemctl --user enable pulseaudio" "Pulseaudio started by systemd"

execute "(cat /usr/share/fzf/key-bindings.zsh | grep \"bindkey '^P' fzf-file-widget\") || \
          sudo sed -i \"s/bindkey '^T' fzf-file-widget/bindkey '^P' fzf-file-widget/g\" \
          /usr/share/fzf/key-bindings.zsh" "Mapping FZF search to CTRL+P"
