#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" &&
  . "./utils"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

declare -r INSTALLED_PACKAGES=$((which yay &> /dev/null && [ ! $? -eq 0 ]) || yay -Q)

install_package_manager() {
  execute "(which yay &> /dev/null && [ $? -eq 0 ] ) || (git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm && cd .. && rm -rf yay)" "YAY"
}

enable_multilib() {
  execute "(cat /etc/pacman.conf | grep -q '^\[multilib\]') || sudo sed -i \"/\[multilib\]/,/Include/\"'s/^#//' /etc/pacman.conf" "Enabling multilib"
}

autoremove() {
  execute "sudo yay -Qtd --noconfirm || true" "YAY (autoremove)"
}

install_ohmyzsh() {
  if [ ! -d "$HOME/.oh-my-zsh" ]; then
    sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  fi
  print_result $? "ohmyzsh"
}

install_nnn_plugins() {
  if [ ! -d "$HOME/.config/nnn/plugins" ]; then
    execute "curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh" "Install NNN plugins"
  fi
  print_result $? "NNN plugins"
}

install_package() {
  declare -r PACKAGE="$1"

  if ! package_is_installed "$PACKAGE"; then
    execute "yay -S --noconfirm --needed $PACKAGE" "$PACKAGE"
  else
    print_success "$PACKAGE"
  fi
}

install_go_package() {
  declare -r PACKAGEPATH="$1"
  declare -r PACKAGENAME="$2"

  execute "go get -u $PACKAGEPATH" "$PACKAGENAME"
}

install_yarn_package() {
  declare -r PACKAGEPATH="$1"
  declare -r PACKAGENAME="$2"

  execute "yarn global add $PACKAGEPATH" "$PACKAGENAME"
}

install_npm_package() {
  declare -r PACKAGENAME="$1"

  execute "npm install -g $PACKAGENAME" "$PACKAGENAME"
}

package_is_installed() {
  echo $INSTALLED_PACKAGES | grep -q " $1 "
}

update() {
  execute "yay -Syyu --noconfirm" "YAY (update)"
}

clean_up_cache() {
  execute "paccache -rk2 && paccache -ruk1" "Clean up cached packages"
}

install_blackarch_repo() {
  if ! yay -Sg | grep -q "^blackarch" &>/dev/null; then
    execute "curl -s https://blackarch.org/strap.sh | sudo bash" "install blackarch repo"
  fi
}
