#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.80           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  00             \
    bottom_padding               00             \
    left_padding                 00             \
    right_padding                00             \
    window_gap                   00             \
    layout                       stack          \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Calculator|Software Update|Dictionary|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|App Store|Steam)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# Workspace management
yabai -m space 1 --label terminal
yabai -m space 2 --label browser
yabai -m space 3 --label chat
yabai -m space 4 --label todo
yabai -m space 5 --label utils

 # Assign apps to spaces
yabai -m rule --add app="kitty" space=terminal
yabai -m rule --add app="Ghostty" space=terminal

yabai -m rule --add app="Firefox" space=browser
yabai -m rule --add app="Google Chrome" space=browser

yabai -m rule --add app="Microsoft Teams" space=chat
yabai -m rule --add app="Discord" space=chat
yabai -m rule --add app="Slack" space=chat
yabai -m rule --add app="Signal" space=chat
yabai -m rule --add app="Messages" space=chat

yabai -m rule --add app="To Do" space=todo
yabai -m rule --add app="Mail" space=todo
yabai -m rule --add app="Calendar" space=todo

yabai -m rule --add app="Spotify" space=utils
yabai -m rule --add app="Sonos" space=utils
yabai -m rule --add app="Remarkable" space=utils
yabai -m rule --add app="Bitwarden" space=utils
yabai -m rule --add app="1Password" space=utils

echo "yabai configuration loaded.."
