#!/bin/bash
#
# Backup script
#

case "$1" in
"do") restic --repo /mnt/usb/restic/ backup ~/.ssh \
    ~/Documents \
    ~/Downloads \
    ~/Pictures \
    ~/logs \
    ~/notes \
    ~/private;;
"snapshots") restic --repo /mnt/usb/restic/ snapshots;;
"prune") restic --repo /mnt/usb/restic/ prune;;
*)            echo "Do nothing" "$@";;
esac
