#!/bin/bash
#
# Backup script
#

BACKUPDIR="/mnt/sdcard/restic/"

case "$1" in
"do") sudo restic --repo "$BACKUPDIR" backup \
  ~/.ssh \
  ~/documents \
  ~/Downloads \
  ~/logs \
  ~/notes \
  ~/pictures \
  ~/private ;;
"list") sudo restic --repo "$BACKUPDIR" snapshots ;;
"prune") sudo restic --repo "$BACKUPDIR" prune ;;
*) echo "Do nothing" "$@" ;;
esac
