#!/bin/bash

declare -r ANSIBLE_CP=`ls $HOME/.ansible/cp/ | grep -v total | awk '{print $9}'`

echo sudo add-apt-repository -y ppa:shevchuk/dnscrypt-proxy
echo sudo add-apt-repository -y ppa:wireguard/wireguard

ssh -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o ConnectTimeout=6 -o ConnectionAttempts=30 -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloudsigma -o ConnectTimeout=60 -o ControlPath=$HOME/.ansible/cp/eeaaa3e7aa -tt $1
