#!/bin/bash
#
# LVM snapshots
#

date=$(date +"%y%m%d")
root="/dev/mapper/lvm-root"
vg="lvm"

case "$1" in
"create") sudo lvcreate --size 10G --snapshot --name backup-$date $root;;
"snapshots") sudo lvs| grep backup;;
"delete") sudo lvremove $vg/$2;;
"restore") sudo lvconvert --merge $vg/$2;;
*)            echo "Do nothing" "$@";;
esac
