#!/bin/bash
#
# Example usage: setup-algo "External-IP-of-the-VPS"
#

declare -r ALGO_DIRECTORY="$HOME/git/algo"

if [ ! -d "$ALGO_DIRECTORY" ]; then
  git clone git@github.com:trailofbits/algo.git
fi

pushd "$ALGO_DIRECTORY" || exit &>/dev/null

git pull -q

python2 -m virtualenv --python="$(command -v python2)" env &&
  source env/bin/activate &&
  python2 -m pip install -U pip virtualenv &&
  python2 -m pip install -r requirements.txt

vi "$ALGO_DIRECTORY"/config.cfg

"$ALGO_DIRECTORY"/algo

deactivate

sudo ln -sf "$ALGO_DIRECTORY"/configs/"$1"/wireguard/laptop.conf /etc/wireguard/wg0.conf

popd || exit &>/dev/null
