blank_issues_enabled: true
contact_links:
  - name: Get help on Discord
    url: https://discord.gg/ohmyzsh
    about: Have a quick question? Join the Discord server and ask on the appropriate channel.
