[metadata]
name = "aws-secrets"
description = "A channel to select from AWS Secrets Manager secrets"
requirements = ["aws"]

[source]
command = "aws secretsmanager list-secrets --query 'SecretList[].[Name,Description]' --output text"

[preview]
command = "aws secretsmanager describe-secret --secret-id '{split:\t:0}' --output json | jq -C"

[ui.preview_panel]
size = 60

