[metadata]
name = "aws-rds"
description = "A channel to select from AWS RDS instances"
requirements = ["aws"]

[source]
command = "aws rds describe-db-instances --query 'DBInstances[].[DBInstanceIdentifier,Engine,DBInstanceStatus]' --output text"

[preview]
command = "aws rds describe-db-instances --db-instance-identifier '{split:\t:0}' --output json | jq -C"

[ui.preview_panel]
size = 60

[keybindings]
enter = "actions:copy"

[actions.copy]
description = "Copy the instance details (preview content) to the clipboard"
command = "aws rds describe-db-instances --db-instance-identifier '{split:\t:0}' --output json | pbcopy"
mode = "fork"

