[metadata]
name = "files"
description = "A channel to select files and directories"
requirements = ["fd", "bat"]

[source]
# Press Ctrl+S to cycle between modes:
# files, gitignored files, hidden + gitignored files,
# directories, gitignored directories, hidden + gitignored directories
command = [
  "fd -t f",
  "fd -t f -I",
  "fd -t f -H -I",
  "fd -t d",
  "fd -t d -I",
  "fd -t d -H -I",
]

[preview]
command = "if test -d '{}'; ls -la '{}'; else; bat -n --color=always '{}'; end"
shell = "fish"
env = { BAT_THEME = "ansi" }

[keybindings]
ctrl-enter = "actions:edit"
ctrl-up = "actions:goto_parent_dir"

[actions.edit]
description = "Opens the selected entries with the default editor (falls back to vim)"
command = "${EDITOR:-vim} {}"
shell = "bash"
# use `mode = "fork"` if you want to return to tv afterwards
mode = "execute"

[actions.goto_parent_dir]
description = "Re-opens tv in the parent directory"
command = "tv files .."
mode = "execute"
