#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make default programs

export BROWSER="firefox"
export EDITOR="nvim"
export FILE="nnn"
export READER="zathura"
export STATUSBAR="i3blocks"
export TERMINAL="alacritty"
export VISUAL="nvim"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Wayland environment variables

# GTK
CLUTTER_BACKEND=wayland
#GDK_BACKEND=wayland             # this can prevent programs from starting (e.g. chromium and electron apps). therefore, this should be set per app instead of globally.
MOZ_ENABLE_WAYLAND=1 # only start firefox in wayland mode and no other GTK apps

# Qt
XDG_SESSION_TYPE=wayland
QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=qt5ct
QT_WAYLAND_FORCE_DPI=physical
QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# elementary
ECORE_EVAS_ENGINE=wayland_egl
ELM_ENGINE=wayland_egl
ELM_DISPLAY=wl
ELM_ACCEL=gl

# clutter
CLUTTER_BACKEND=wayland

# sdl
SDL_VIDEODRIVER=wayland

# java
_JAVA_AWT_WM_NONREPARENTING=1

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Ignore commands that start with spaces and duplicates.

export HISTCONTROL=ignoreboth:erasedups

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Increase the maximum number of lines of history
# persisted in the history file.

export HISTFILESIZE=30000

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Don't add certain commands to the history file.

export HISTIGNORE="&:[bf]g:c:clear:history:exit:q:pwd:ls:cd ..:* --help"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Increase the maximum number of commands recorded
# in the command history.

export HISTSIZE=30000

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Use custom `less` colors for `man` pages.

export LESS_TERMCAP_md="$(
  tput bold 2>/dev/null
  tput setaf 2 2>/dev/null
)"
export LESS_TERMCAP_me="$(tput sgr0 2>/dev/null)"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Don't clear the screen after quitting a `man` page.

export MANPAGER="less -X"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Add my scripts to PATH.

export PATH=$HOME/.local/bin:$PATH

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history.

#export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
if [ ! -z "$PROMPT_COMMAND" ]; then
  export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make Python use UTF-8 encoding for output to stdin/stdout/stderr.

export PYTHONIOENCODING="UTF-8"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# For Go development

export GOPATH=$HOME/go
export PATH=$PATH:/usr/lib/go/bin:$GOPATH/bin

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# FZF options

export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border "

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_R_OPTS='--sort --exact'
export FZF_CTRL_T_OPTS="--preview 'cat {}'"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# SSH environment file

export SSH_ENV="$HOME/.ssh/environment"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# nnn settings

export NNN_SSHFS_OPTS="sshfs -o follow_symlinks"
export NNN_USE_EDITOR=1
export NNN_CONTEXT_COLORS="2136"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Grim settings

export GRIM_DEFAULT_DIR="$HOME/Pictures/screenshots"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Use dmenu for sudo pass insert

export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
