#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'
alias g="git"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll='ls -alF'
alias l='ls -CF'
alias logme="script -f $HOME/logs/$(date +"%d-%b-%y_%H-%M-%S")_shell.log"
alias ls='ls -l --color=auto'
alias m="man"
alias map="xargs -n1"
alias mc='. /usr/share/mc/bin/mc-wrapper.sh'
alias mkdir='mkdir -p -v'
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias ping='ping -c 5'
alias q="exit"
alias :q="exit"
alias t="tmux"
alias diff='colordiff' # requires colordiff package
alias rm='rm -I' # 'rm -i' prompts for every file
alias vi='nvim'
alias vim='nvim'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Lock screen.

alias afk="gnome-screensaver-command --lock"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for the `Advanced Packaging Tool`

alias apti="sudo apt install"
alias aptr="sudo apt remove"
alias apts="sudo apt search"
alias aptu="sudo apt update \
            && sudo apt upgrade \
            && sudo apt autoremove"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Empty trash.

alias empty-trash="rm -rf ~/.local/share/Trash/files/*"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Hide/Show desktop icons.

alias hide-desktop-icons="gsettings set org.gnome.desktop.background show-desktop-icons false"
alias show-desktop-icons="gsettings set org.gnome.desktop.background show-desktop-icons true"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Get local IP.

alias local-ip="ifconfig \
                    | grep 'inet addr' \
                    | grep -v '127.0.0.1' \
                    | cut -d: -f2 \
                    | cut -d' ' -f1"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Open from the terminal.

alias o="xdg-open"
