#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files() {

  declare -r CURRENT_DIRECTORY="$(pwd)"

  declare -r -a FILES_TO_SOURCE=(
    "bash_aliases"
    "bash_autocomplete"
    "bash_exports"
    "bash_functions"
    "bash_options"
    "bash_prompt"
    "bash.local" # For local settings that should
    # not be under version control.
  )

  local file=""
  local i=""

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")" &&
    . "../os/utils"

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  for i in ${!FILES_TO_SOURCE[*]}; do

    file="$HOME/.${FILES_TO_SOURCE[$i]}"

    [ -r "$file" ] &&
      . "$file"

  done

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  cd "$CURRENT_DIRECTORY"

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files
unset -f source_bash_files

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Source other files

source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Source SSH settings, if applicable

if [ -f "${SSH_ENV}" ]; then
  . "${SSH_ENV}" >/dev/null
  #ps ${SSH_AGENT_PID} doesn't work under cywgin
  ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ >/dev/null || {
    start_agent
  }
else
  start_agent
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# History file tweaks

tac $HISTFILE | awk '!x[$0]++' | tac | sponge $HISTFILE

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Clear system messages (system copyright notice, the date
# and time of the last login, the message of the day, etc.).

clear
