#!/bin/zsh

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make default programs

export BROWSER="firefox"
export EDITOR="nvim"
export FILE="nnn"
export READER="zathura"
export STATUSBAR="i3blocks"
export TERMINAL="alacritty"
export VISUAL="nvim"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Set cursor theme

export XCURSOR_THEME="Adwaita"
export XCURSOR_SIZE="24"
export SWAY_CURSOR_THEME="Adwaita"
export SWAY_CURSOR_SIZE="24"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Ignore commands that start with spaces and duplicates.

export HISTCONTROL=ignoreboth:erasedups

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Increase the maximum number of lines of history
# persisted in the history file.

export HISTFILESIZE=30000

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Don't add certain commands to the history file.

export HISTIGNORE="&:[bf]g:c:clear:history:exit:q:pwd:ls:cd ..:* --help"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Increase the maximum number of commands recorded
# in the command history.

export HISTSIZE=30000

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Use custom `less` colors for `man` pages.

export LESS_TERMCAP_md="$(
  tput bold 2>/dev/null
  tput setaf 2 2>/dev/null
)"
export LESS_TERMCAP_me="$(tput sgr0 2>/dev/null)"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Don't clear the screen after quitting a `man` page.

export MANPAGER="less -X"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Add my scripts to PATH.

export PATH=$HOME/.local/bin:$PATH

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history.

if [ ! -z "$PROMPT_COMMAND" ]; then
  export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make Python use UTF-8 encoding for output to stdin/stdout/stderr.

export PYTHONIOENCODING="UTF-8"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# For Go development

export GOPATH=$HOME/go
export PATH=$PATH:/usr/lib/go/bin:$GOPATH/bin

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# FZF options

export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border "

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_R_OPTS='--sort --exact'
export FZF_CTRL_T_OPTS="--preview 'cat {}'"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# SSH environment file

export SSH_ENV="$HOME/.ssh/environment"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# nnn settings

export NNN_SSHFS_OPTS="sshfs -o follow_symlinks"
export NNN_USE_EDITOR=1
export NNN_CONTEXT_COLORS="2136"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Grim settings

export GRIM_DEFAULT_DIR="$HOME/pictures/screenshots"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Use dmenu for sudo pass insert

export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
