#!/bin/zsh

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias c="clear"
alias chgrp='chgrp --preserve-root'
alias chmod='chmod --preserve-root'
alias chown='chown --preserve-root'
alias diff='colordiff'
alias g="git"
alias lg='lazygit'
alias ls='exa'
alias logme="script -f $HOME/logs/$(date +"%d-%b-%y_%H-%M-%S")_shell.log"
alias mkdir='mkdir -p -v'
alias N='sudo -E nnn -deH'
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias ping='ping -c 5'
alias q="exit"
alias rm='rm -I'
alias yaegi='rlwrap yaegi'
alias vi='nvim'
alias vim='nvim'
alias :q="exit"

alias get-local-ip="ifconfig \
                    | grep 'inet ' \
                    | grep -v '127.0.0.1' \
                    | awk '{print $2}'"

alias get-ext-ip="curl ipinfo.io/ip"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
