#!/bin/bash

SOURCE_DIR=$(chezmoi source-path)

. "$SOURCE_DIR/scripts/utils"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

install_fish_plugin() {
  declare -r PACKAGEPATH="$1"
  declare -r PACKAGENAME="$2"

  execute "fish -c \"fisher install $PACKAGEPATH\"" "$PACKAGENAME"
}

install_go_package() {
  declare -r PACKAGEPATH="$1"
  declare -r PACKAGENAME="$2"

  execute "go install $PACKAGEPATH" "$PACKAGENAME"
}

install_npm_package() {
  declare -r PACKAGENAME="$1"

  execute "npm install -g $PACKAGENAME" "$PACKAGENAME"
}

install_rust_package() {
  declare -r PACKAGENAME="$1"

  execute "cargo install $PACKAGENAME" "$PACKAGENAME"
}

install_pip_package() {
  declare -r PACKAGENAME="$1"

  execute "pip install --upgrade $PACKAGENAME" "$PACKAGENAME"
}

install_gh_plugin() {
  declare -r PLUGIN="$1"
  declare -r INSTALLED_PLUGINS=$(gh extension list)

  if ! echo $INSTALLED_PLUGINS | grep -q $PLUGIN; then
    execute "gh extension install $PLUGIN" "$PLUGIN"
  else
    print_success "$PLUGIN"
  fi
}
