#!/bin/bash

SOURCE_DIR=$(chezmoi source-path)

. "$SOURCE_DIR/scripts/utils"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

declare -r INSTALLED_PACKAGES=$(dnf list --installed)

install_nnn_plugins() {
	script_path="$HOME/.config/nnn/plugins/getplugs"

	if [ ! -f "$script_path" ]; then
		wget https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs -O "$script_path"
	fi

	bash "$script_path"

	rm -rf "$HOME/.config/nnn/*.tar.gz"

	print_result $? "Install/update nnn plugins"
}

install_package() {
	declare -r PACKAGE="$1"

	if ! package_is_installed "$PACKAGE"; then
		execute "sudo dnf install -y $PACKAGE" "$PACKAGE"
	else
		print_success "$PACKAGE"
	fi
}

install_fish_plugin() {
	declare -r PACKAGEPATH="$1"
	declare -r PACKAGENAME="$2"

	execute "fish -c \"fisher install $PACKAGEPATH\"" "$PACKAGENAME"
}

install_go_package() {
	declare -r PACKAGEPATH="$1"
	declare -r PACKAGENAME="$2"

	execute "go install $PACKAGEPATH" "$PACKAGENAME"
}

install_npm_package() {
	declare -r PACKAGENAME="$1"

	execute "sudo npm install -g $PACKAGENAME" "$PACKAGENAME"
}

install_rust_package() {
	declare -r PACKAGENAME="$1"

	execute "cargo install $PACKAGENAME" "$PACKAGENAME"
}

install_pip_package() {
	declare -r PACKAGENAME="$1"

	execute "pip install --upgrade $PACKAGENAME" "$PACKAGENAME"
}

install_gh_plugin() {
	declare -r PLUGIN="$1"
	declare -r INSTALLED_PLUGINS=$(gh extension list)

	if ! echo $INSTALLED_PLUGINS | grep -q $PLUGIN; then
		execute "gh extension install $PLUGIN" "$PLUGIN"
	else
		print_success "$PLUGIN"
	fi
}

package_is_installed() {
	echo $INSTALLED_PACKAGES | grep -q " $1 "
}

clean_up_unused_packages() {
	sudo dnf autoremove
}
